version: "3"
services: 
  node-server:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=nhatnguyen
      - MONGO_PASSWORD=mypassword
    command: npm run start-dev
    depends_on: 
      - mongodb
    restart: always
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nhatnguyen
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes: 
      - mongodb:/data/db
    restart: always
volumes:
  mongodb: