version: "3"
services: 
  node-server:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js
    depends_on: 
      - mongodb
    restart: always
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes: 
      - mongodb:/data/db
    restart: always
volumes:
  mongodb: