version: "3"

services:
  node-server-1:
    build: .
    container_name: node-1
    ports:
      - "1111:3000"
    environment:
      - APPID=node-1
    depends_on: 
      - mongodb
    volumes:
      - ./public/storage/images:/app/public/storage/images
    restart: always
  node-server-2:
    build: .
    container_name: node-2
    environment:
      - APPID=node-2
    ports:
      - "2222:3000"
    depends_on: 
      - mongodb
    volumes:
      - ./public/storage/images:/app/public/storage/images
    restart: always
  node-server-3:
    build: .
    container_name: node-3
    environment:
      - APPID=node-3
    ports:
      - "3333:3000"
    depends_on: 
      - mongodb
    volumes:
      - ./public/storage/images:/app/public/storage/images
    restart: always
  node-server-4:
    build: .
    container_name: node-4
    environment:
      - APPID=node-4
    ports:
      - "4444:3000"
    depends_on: 
      - mongodb
    volumes:
      - ./public/storage/images:/app/public/storage/images
    restart: always
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nhatnguyen
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes: 
      - mongodb:/data/db
    restart: always
  redis:
    image: redis:6.2.3
volumes:
  mongodb:
  

