name: CI to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Build the images
      
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml build node-server
      # List images
      - name: List images
        run: docker images
      # List container
      - name: List containers
        run: docker ps -a
      # Push images
      - name: Push images
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml push node-server
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}